name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  php-tests:
    name: PHPStan and Pest on PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ 7.4, 8.0, 8.1, 8.2, 8.3, 8.4 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Install Perfbase
        run: bash -c "$(curl -fsSL https://cdn.perfbase.com/install.sh)"

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=1G

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
